In [ ]:
# 1. Import numpy as np
import numpy as np

In [ ]:
# 2. Print numpy version and configuration
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

In [ ]:
# 3. Create a null vector of size 10
v3 = np.zeros(10)
v3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 4. Find the memory size of any array
print("memory size (bytes):", v3.nbytes)

memory size (bytes): 80


In [ ]:
# 6. Null vector of size 10 with fifth value = 1
v6 = np.zeros(10)
v6[4] = 1
v6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# 7. Vector with values from 10 to 49
v7 = np.arange(10, 50)
v7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 8. Reverse a vector
v8 = v7[::-1]
v8

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
m9 = np.arange(9).reshape(3, 3)
m9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr10 = np.array([1, 2, 0, 0, 4, 0])
nz10 = np.nonzero(arr10)
nz10

(array([0, 1, 4]),)

In [ ]:
# 11. 3x3 identity matrix
m11 = np.eye(3)
m11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 12. 3x3x3 array with random values
a12 = np.random.random((3, 3, 3))
a12

array([[[4.86055333e-02, 4.48930730e-01, 7.70596221e-01],
        [1.79665523e-01, 2.26230770e-02, 5.39558273e-01],
        [1.00812541e-01, 4.89577546e-01, 9.17971327e-04]],

       [[1.96644348e-01, 4.41972816e-01, 9.02148056e-01],
        [7.35594536e-01, 1.04564161e-01, 6.35174884e-01],
        [6.66975670e-01, 8.07667712e-01, 6.44979616e-01]],

       [[3.55479270e-02, 1.29946164e-01, 1.79638477e-02],
        [5.02113171e-01, 3.53820349e-01, 9.78628149e-01],
        [8.06623121e-01, 6.35661111e-01, 7.66563814e-01]]])

In [ ]:
# 13. 10x10 random array and min/max
a13 = np.random.random((10, 10))
print("min =", a13.min(), "max =", a13.max())

min = 0.004317311014870762 max = 0.987585080107477


In [ ]:
# 14. Random vector of size 30 and mean
v14 = np.random.random(30)
print("mean =", v14.mean())

mean = 0.3763143336008759


In [ ]:
# 15. 2D array with 1 on border and 0 inside
a15 = np.ones((5, 5))
a15[1:-1, 1:-1] = 0
a15

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 16. Add a zero border around an existing array
a16 = np.pad(a15, pad_width=1, mode='constant', constant_values=0)
a16

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# 17. Results of expressions
print(0 * np.nan)             # nan
print(np.nan == np.nan)       # False
print(np.inf > np.nan)        # False
print(np.nan - np.nan)        # nan
print(np.nan in set([np.nan]))# True
print(0.3 == 3 * 0.1)         # False

nan
False
False
nan
True
False


In [ ]:
# 18. 5x5 matrix with values 1,2,3,4 below the diagonal
m18 = np.diag([1, 2, 3, 4], k=-1)
m18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# 19. 8x8 checkerboard pattern
checker19 = np.zeros((8, 8), dtype=int)
checker19[1::2, ::2] = 1
checker19[::2, 1::2] = 1
checker19

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# 20. Index of the 100th element in a (6,7,8) array
idx20 = np.unravel_index(99, (6, 7, 8))
idx20

(np.int64(1), np.int64(5), np.int64(3))

In [ ]:
# 21. Checkerboard using tile
checker21 = np.tile([[0, 1], [1, 0]], (4, 4))
checker21

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
# 22. Normalize a 5x5 random matrix
a22 = np.random.random((5, 5))
a22 = (a22 - a22.min()) / (a22.max() - a22.min())
a22

array([[0.46227369, 0.64499904, 0.74334608, 0.09698032, 0.43802843],
       [0.80907717, 0.43466082, 0.87711247, 0.28928716, 0.17846524],
       [0.1485331 , 0.75700247, 0.61769183, 0.95991642, 0.52804075],
       [1.        , 0.8102827 , 0.2775552 , 0.07722996, 0.34293218],
       [0.24220543, 0.83724921, 0.65198576, 0.94149404, 0.        ]])

In [ ]:
# 23. Custom dtype for RGBA
color_dtype = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])
color_dtype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [ ]:
# 24. Multiply 5x3 matrix by 3x2 matrix
A = np.random.random((5, 3))
B = np.random.random((3, 2))
C = A @ B
C

array([[0.44690615, 0.54922419],
       [0.22374043, 0.10585786],
       [0.74709224, 0.34298494],
       [0.47737492, 0.6012752 ],
       [0.94435348, 0.31794878]])

In [ ]:
# 25. Negate elements between 3 and 8 (in place)
arr25 = np.array([1, 4, 6, 9, 2, 7])
arr25[(arr25 > 3) & (arr25 < 8)] *= -1
arr25

array([ 1, -4, -6,  9,  2, -7])

In [ ]:
# 26. Output of the following script
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


In [ ]:
# 28. Results of expressions
print(np.array(0) / np.array(0))                # nan
print(np.array(0) // np.array(0))               # 0 (warning)
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipython-input-2198637125.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))                # nan
/tmp/ipython-input-2198637125.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))               # 0 (warning)
/tmp/ipython-input-2198637125.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [ ]:
# 29. Round away from zero
Z29 = np.array([-1.2, 1.2, -2.7, 2.7])
Z29_round = np.copysign(np.ceil(np.abs(Z29)), Z29)
Z29_round


array([-2.,  2., -3.,  3.])

In [ ]:
# 30. Find common values between two arrays
A30 = np.array([1, 2, 3, 4])
B30 = np.array([3, 4, 5, 6])
np.intersect1d(A30, B30)

array([3, 4])

In [ ]:
# 31. Ignore all numpy warnings
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [ ]:
# 32. Is the expression true?
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [ ]:
# 33. Yesterday, today and tomorrow
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2026-02-04 2026-02-05 2026-02-06


In [ ]:
# 34. Dates of July 2016
dates34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates34

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
# 35. Compute ((A+B)*(-A/2)) in place
A35 = np.random.random((3, 3))
B35 = np.random.random((3, 3))
np.add(A35, B35, out=A35)
np.multiply(A35, -A35/2, out=A35)
A35

array([[-0.36232687, -0.21280946, -0.13029391],
       [-0.89228321, -0.04577989, -1.06244671],
       [-1.15529629, -1.62778808, -0.53619962]])

In [ ]:
# 36. Extract integer part (4 methods)
Z36 = np.random.random(10) * 10
print(np.floor(Z36))
print(np.trunc(Z36))
print(Z36.astype(int))
print(Z36 // 1)

[9. 7. 6. 6. 6. 8. 5. 7. 1. 2.]
[9. 7. 6. 6. 6. 8. 5. 7. 1. 2.]
[9 7 6 6 6 8 5 7 1 2]
[9. 7. 6. 6. 6. 8. 5. 7. 1. 2.]


In [ ]:
# 37. 5x5 matrix with rows 0 to 4
M37 = np.tile(np.arange(5), (5, 1))
M37

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
# 38. Build array from generator
def gen38():
    for i in range(10):
        yield i
A38 = np.fromiter(gen38(), dtype=int)
A38

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 39. Vector of size 10 with values in (0,1)
V39 = np.linspace(0, 1, 12)[1:-1]
V39

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
# 40. Random vector and sort
V40 = np.random.random(10)
V40.sort()
V40

array([0.03722797, 0.12528927, 0.185554  , 0.28487191, 0.30511823,
       0.31076037, 0.32388752, 0.44175394, 0.48020792, 0.61450479])

In [ ]:
# 41. Sum faster than np.sum for small arrays
Z41 = np.arange(10)
np.add.reduce(Z41)

np.int64(45)

In [ ]:
# 42. Check if two arrays are equal
A42 = np.array([1, 2, 3])
B42 = np.array([1, 2, 3])
np.array_equal(A42, B42)

True

In [ ]:
# 43. Make array immutable
Z43 = np.array([1, 2, 3])
Z43.flags.writeable = False
Z43.flags.writeable

False

In [ ]:
# 44. Cartesian to polar coordinates
Z44 = np.random.random((10, 2))
x, y = Z44[:, 0], Z44[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("r =", r, "\ntheta =", theta)

r = [0.20124227 0.64967589 0.79153472 0.48831495 0.90784664 1.07553183
 0.59458573 0.515713   0.67189543 1.15503865] 
theta = [1.4258088  1.35071743 1.51764692 1.07398544 0.83733867 0.7560973
 0.30674535 0.70450382 1.23922479 0.99752435]


In [ ]:
# 45. Replace maximum value with 0
Z45 = np.random.random(10)
Z45[Z45.argmax()] = 0
Z45

array([0.56228754, 0.09890942, 0.50642495, 0.85754133, 0.2494415 ,
       0.        , 0.60066971, 0.86568945, 0.09982981, 0.84337149])

In [ ]:
# 46. Structured array with x,y in [0,1]x[0,1]
x46, y46 = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
Z46 = np.zeros(x46.shape, dtype=[('x', float), ('y', float)])
Z46['x'], Z46['y'] = x46, y46
Z46

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
# 47. Cauchy matrix
X47 = np.array([1, 2, 3])
Y47 = np.array([4, 5, 6])
C47 = 1.0 / (X47[:, None] - Y47[None, :])
C47

array([[-0.33333333, -0.25      , -0.2       ],
       [-0.5       , -0.33333333, -0.25      ],
       [-1.        , -0.5       , -0.33333333]])

In [ ]:
# 48. Min and max representable values
for dtype in [np.int8, np.int16, np.int32, np.int64,
              np.uint8, np.uint16, np.uint32, np.uint64,
              np.float32, np.float64]:
    info = np.iinfo(dtype) if np.issubdtype(dtype, np.integer) else np.finfo(dtype)
    print(dtype, info.min, info.max)

<class 'numpy.int8'> -128 127
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.uint8'> 0 255
<class 'numpy.uint16'> 0 65535
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.float32'> -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> -1.7976931348623157e+308 1.7976931348623157e+308


In [ ]:
# 49. Print all values of an array
np.set_printoptions(threshold=np.inf)
print(C47)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [ ]:
# 50. Closest value to a scalar
Z50 = np.array([0.1, 0.4, 0.8, 1.2])
value = 0.9
closest = Z50[np.abs(Z50 - value).argmin()]
closest

np.float64(0.8)